### ISSUE TITLE
Inconsistent Email links

### ISSUE THREAD

**Issue by linuxdaemon** [snoonetIRC/website#92]
In some pages on the site, we link emails to their `mailto:` links, in other places we don't, and in some we obscure the emails with `name [at] snoonet.org` manually

**Comment by n7st** [comment]
@snoonetIRC/website shall we standardise on the former or latter? I'd be tempted to choose `name [at] snoonet.org` (I use that format on my own staff page already).

I can add a shortcode for e-mail links in the meantime and will open a pull request.
